# Generated by Django 2.2.7 on 2020-01-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseattendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
